name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Use .NET 2.2.108
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
          
      - name: Building
        run: dotnet build --configuration Debug
          
      - name: Run Tests
        run: dotnet test
